kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: canary-check
spec:
  args:
  - name: stable-hash
  - name: latest-hash
  #- name: rollout-status  
  metrics:
  - name: test
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              # containers:
              # - name: busybox
              #   image: busybox
              #   #args: [test]  #--> for making analysis fail, uncomment                     
              containers:
              - name: hello
                image: busybox:latest
                command: ['sh', '-c', 'echo "[Debug] Latest: {{ args.latest-hash }} Stable: {{ args.stable-hash }}" && sleep 3600']              
              restartPolicy: Never